### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by AlexandreBroudin** [livingstyleguide/broccoli-livingstyleguide#1]
This is what I got in terminal
`bundle exec livingstyleguide compile app/styles/styleguide.lsg /Users/Alexandre/Sites/project/tmp/living_style_guide_compiler-tmp_dest_dir-UcQsq2LD.tmp/templates/styleguide/index.hbs
broccoli-livingstyleguide exited with error code 10 [string exception]`

**Comment by bluSCALE4** [comment]
I get the same error following the Ember-CLI instructions.

``` log
bundle exec livingstyleguide compile app/styles/styleguide.lsg /Users/luis/Sites/test-cli/tmp/living_style_guide_compiler-tmp_dest_dir-qsfJDzc0.tmp/assets/styleguide.html
broccoli-livingstyleguide exited with error code 10 [string exception]
Error: broccoli-livingstyleguide exited with error code 10 [string exception]
    at wrapStringErrors (/Users/luis/Sites/test-cli/node_modules/ember-cli/node_modules/broccoli/lib/builder.js:18:11)
    at lib$rsvp$$internal$$tryCatch (/Users/luis/Sites/test-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/luis/Sites/test-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/luis/Sites/test-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$$internal$$publishRejection (/Users/luis/Sites/test-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:419:7)
    at lib$rsvp$asap$$flush (/Users/luis/Sites/test-cli/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by hagenburger** [comment]
I could not reproduce this yet. Would it be possible to provide an example project?

Also: Which versions of `livingstyleguide`, `broccoli-livingstyleguide`, `ember-cli`, and `broccoli` are you using?
